apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: cluster-rolebinding
  namespace: security-app
subjects:
  - kind: ServiceAccount
    name: cluster-reader-sa
    namespace: security-app
roleRef:
  kind: ClusterRole
  name: cluster-pod-reader
  apiGroup: rbac.authorization.k8s.io
