apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: security-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      imagePullSecrets:
        - name: security-app
      containers:
        - name: backend
          image: sohila12/k8s-security-backend:1.0
          imagePullPolicy: IfNotPresent
          args:
            - "-text=Hello from backend"
          ports:
            - containerPort: 5678
