apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: security-app
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata: 
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: frontend
          image: nginx:alpine
          ports:
            - containerPort: 80
